### ISSUE TITLE
Output folder stocked in working dir

### ISSUE THREAD

**Issue by spirillen** [PyFunceble-Templates/pyfunceble-miniconda#3]
For some reason the `output` directory is not pushed to the `${outputDir}`

See also <https://github.com/funilrys/PyFunceble/issues/93>

**Comment by spirillen** [comment]
The problem seems to be that the outdir location does not honor  `PYFUNCEBLE_CONFIG_DIR` which should be the "top" working dir for the test enviroment

sources: https://pyfunceble.readthedocs.io/en/dev/components/output-files.html, https://pyfunceble.readthedocs.io/en/dev/components/environment-variables.html?highlight=PYFUNCEBLE_CONFIG_DIR

**Comment by funilrys** [comment]
@spirillen You are confusing config directory with output directory.

The config directory is where PyFunceble is expected to find or generate its configuration file(s).

As per https://github.com/funilrys/PyFunceble/issues/94 it is now (PyFunceble-dev at the time I write this) possible to define where you want to generate the `output/` directory per [`PYFUNCEBLE_OUTPUT_LOCATION`](https://pyfunceble.readthedocs.io/en/dev/components/environment-variables.html?highlight=PYFUNCEBLE_OUTPUT_LOCATION) environment variable.

**Comment by spirillen** [comment]
I can see the mistake now...

I was reading the `PYFUNCEBLE_OUTPUT_DIR` not the `PYFUNCEBLE_OUTPUT_LOCATION` that's the reason to all of this.

Will fix this soonest possible

**Comment by spirillen** [comment]
Self note:

As miniconda has moved on then we need to replace the source command for activating ENV with conda, just as to deactivate.

See also cheetSheet https://docs.conda.io/projects/conda/en/latest/_downloads/843d9e0198f2a193a3484886fa28163c/conda-cheatsheet.pdf
[conda-cheatsheet.pdf](https://app.gitkraken.com/api/glo/boards/5ed6678bc2baa00011109fbd/attachments/5edbb32ee4d13200110797f7)
